# Generated by Django 4.1 on 2022-08-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RotaryclubVolunteerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=50)),
                ('past_socialwork', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
